src/main/java/org/jinstagram/Instagram.java
src/main/java/org/jinstagram/http/Request.java

This commit adds support for an outbound http proxy when making
a request. If the http.proxyHost and http.proxyPort system
properties are non null, then the request will be open with a
Proxy defined by those values.

Allow use of Proxy on Requests

---

src/main/java/org/jinstagram/auth/oauth/InstagramService.java

Currently to get an `org.jinstagram.Instagram` object with enforce signed header we need to provide our api secret as an argument.
I would like this info to be stored only in our `org.jinstagram.auth.oauth.InstagramService` object and not in the class that creates the Instagram object.
A solution is to provide methods that directly returns the Instagram object. This way we don't need to store the secret anywhere else.

Methods to get Instagram objects from the class InstagramService

---

src/main/java/org/jinstagram/Instagram.java

There are some Instagram APIs that doesn't handle well non-URL-encoded requests. For example, when I run the following request:
curl -XGET "https://api.instagram.com/v1/tags/paixão/media/recent?access_token=ACCESS-TOKEN"
I get the following result body:
<body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>
The body returned is HTML, thus can't be parsed as JSON.
The method Instagram.handleInstagramError() should throw an InstagramException stating that it can't decode the error message.  But because the exception constructor is calling response.getBody() a second time, the following exception is being thrown:
java.lang.IllegalStateException: Error while reading response body
at org.jinstagram.http.StreamUtils.getStreamContents(StreamUtils.java:42)
at …

Better error handling in case of invalid JSON returned by Instagram API

---

src/main/java/org/jinstagram/Instagram.java
src/test/java/org/jinstagram/InstagramTest.java

According to https://instagram.com/developer/limits/ and some testing in real project Limit Exception should be raised in case of HTTP code 429, but not 503 (as in original code). So I made a little fix and a test to check it at least on code level.

correct response code for out of limit situation

---

src/main/java/org/jinstagram/utils/LogHelper.java

This utility method is doing a lot of work (parsing a json, serializing it)
despite that the logger could not have debugging enable.
Also the method get call despite of the media type of the response.
There are cases where if get recent media from a user that does not exists
the 404 response is of media html. In those cases the method fails

LogHelper#prettyPrintJSONResponse lean and safer

---

src/main/java/org/jinstagram/Instagram.java
src/main/java/org/jinstagram/model/Methods.java
src/main/java/org/jinstagram/realtime/InstagramSubscription.java
src/main/java/org/jinstagram/realtime/SubscriptionResponse.java
src/main/java/org/jinstagram/realtime/SubscriptionResponseData.java
src/main/java/org/jinstagram/realtime/SubscriptionResponseObject.java
src/main/java/org/jinstagram/realtime/SubscriptionType.java
src/main/java/org/jinstagram/realtime/SubscriptionUtil.java
src/main/java/org/jinstagram/realtime/SubscriptionsListResponse.java
src/test/java/org/jinstagram/InstagramTest.java
src/test/java/org/jinstagram/realtime/SubscriptionUtilTest.java

Closing issue #130. Still need to deprecate
See: https://www.instagram.com/developer/changelog/ on Nov 17, 2015.
* Deprecation of /users/self/feed
* Deprecation of /media/popular
* Deprecation of /geographies/media/recent
* Deprecation of Realtime subscriptions for tags, locations and geographies
Added deprecated annotation and tags on methods using deprecated api.
Added deprecated annotations on classes of realtime package.
Added getUsersRecentMedia methods to replace getUserFeeds.

Managing deprecation of three api requests. Issue #130

---

src/main/java/org/jinstagram/model/Methods.java

I've found two endpoints which fail the signature validation: https://www.instagram.com/developer/secure-api-requests/
Both endpoints fail due to a trailing slash, which Instagram must remove on their end as part of the signature validation. Removing the slash allows the endpoints to pass signature validation, which is what this PR does.

Failing secure requests

---

src/main/java/org/jinstagram/Instagram.java
src/main/java/org/jinstagram/InstagramOembed.java

This pull request is focused on resolving occurrences of Sonar rule squid:S1488 Local Variables should not be declared and then immediately returned or thrown
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1488
George Kankava

squid:S1488 Local Variables should not be declared and then immediately returned or thrown

---

src/main/java/org/jinstagram/entity/common/VideoData.java
src/main/java/org/jinstagram/utils/LogHelper.java

This pull request is focused on resolving occurrences of Sonar rule squid:S1213 - The members of an interface declaration or class should appear in a pre-defined order.
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1213
George Kankava

squid:S1213 - The members of an interface declaration or class should appear in a pre-defined order

---

src/main/java/org/jinstagram/auth/oauth/InstagramService.java
src/main/java/org/jinstagram/http/Request.java
src/main/java/org/jinstagram/http/URLUtils.java
src/main/java/org/jinstagram/utils/LogHelper.java
src/test/java/org/jinstagram/InstagramAuthenticationTest.java

This pull request is focused on resolving occurrences of Sonar rule
squid:S2864 - "entrySet()" should be iterated when both the key and value are needed.
squid:S1172 - Unused method parameters should be removed.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS2864
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1172
George Kankava

Multiple code improvements 1

---

src/main/java/org/jinstagram/exceptions/InstagramException.java
src/test/java/org/jinstagram/exceptions/InstagramExceptionTest.java

It appeared there is no way to get errorType from an exception rather then parse it from a message. It will be very handy for smart handling of different types of errors like `APINotAllowedError `.

errorType getter

---

src/main/java/org/jinstagram/Instagram.java
src/main/java/org/jinstagram/InstagramOembed.java

This pull request is focused on resolving occurrences of Sonar rules
squid:S1192 - String literals should not be duplicated.
squid:S2325 - "private" methods that don't access instance data should be "static".
https://dev.eclipse.org/sonar/rules/show/squid:S1192
https://dev.eclipse.org/sonar/rules/show/squid:S2325
George Kankava

Multiple code improvements: squid:S1192, squid:S2325

---

src/main/java/org/jinstagram/http/APILimitUtils.java
src/main/java/org/jinstagram/http/StreamUtils.java
src/main/java/org/jinstagram/http/URLUtils.java

This pull request is focused on resolving occurrences of Sonar rules
squid:S00105 Tabulation characters should not be used,
squid:S1118 Utility classes should not have public constructors.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS00105
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1118
George Kankava

multiple code improvements: squid:S00105, squid:S1118

---

src/main/java/org/jinstagram/auth/model/Constants.java
src/main/java/org/jinstagram/auth/model/OAuthConfig.java
src/main/java/org/jinstagram/auth/model/OAuthConstants.java
src/main/java/org/jinstagram/auth/model/OAuthRequest.java
src/main/java/org/jinstagram/auth/oauth/InstagramService.java

This pull request is focused on resolving occurrences of Sonar rules
quid:S00105 Tabulation characters should not be used,
squid:S1118 Utility classes should not have public constructors,
squid:ClassVariableVisibilityCheck Class variable fields should not have public accessibility,
squid:S2325 "private" methods that don't access instance data should be "static".
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS00105
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1118
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AClassVariableVisibilityCheck
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS2325
George Kankava

multiple code improvements: squid:S00105, squid:S1118, squid:ClassVariableVisibilityCheck, squid:S2325

---

src/main/java/org/jinstagram/Instagram.java
src/main/java/org/jinstagram/InstagramConfig.java
src/main/java/org/jinstagram/InstagramObject.java
src/main/java/org/jinstagram/InstagramOembed.java
src/main/java/org/jinstagram/InstagramResponse.java

This pull request is focused on resolving occurrences of Sonar rules
squid:S2325 "private" methods that don't access instance data should be "static", 
squid:EmptyStatementUsageCheck Empty statements should be removed, 
squid:S00105 Tabulation characters should not be used
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS2325
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AEmptyStatementUsageCheck
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS00105
George Kankava

multiple code improvements: squid:S2325, squid:EmptyStatementUsageCheck, squid:S00105

---

src/main/java/org/jinstagram/http/APILimitUtils.java
src/test/java/org/jinstagram/http/APILimitUtilsTest.java

It appeared Instagram responses contain headers in lower case. Added some logic to check for a lower case header if an original one wasn't found.

check for a lower case header

---

src/main/java/org/jinstagram/Instagram.java
src/main/java/org/jinstagram/utils/PaginationHelper.java

When using signed requests, the endpoint name must not include the query string.  Currently the query string is not stripped when using Pagination.getNextUrl().
Additionally, the old *sig* param from the prior request is part of that query string & must be removed so that it is included in the HMAC.

Fix pagination with signed requests

---

src/main/java/org/jinstagram/Instagram.java
src/main/java/org/jinstagram/http/URLUtils.java
src/main/java/org/jinstagram/utils/PaginationHelper.java

Hashtags with characters that require URI encoding (e.g. #señor) need to be signed un-encoded.
Credit to Gagan Jain @ Sprinklr for the original fix.
Fixes #168

Handle URI-encoded tags when signing requests

---

src/main/java/org/jinstagram/Instagram.java
src/main/java/org/jinstagram/auth/InstagramApi.java
src/test/java/org/jinstagram/auth/InstagramApiTest.java

Econde on instagram should be something like this "likes+comments" and formURLEncoded broke it.

Correction on Scope authorization url and overload getRecentMediaByLocation

---

src/main/java/org/jinstagram/InstagramBase.java
src/main/java/org/jinstagram/InstagramClient.java
src/main/java/org/jinstagram/entity/tags/TagMediaFeed.java

*Motivation*
TagMediaFeed encapsulates exactly the same state as MediaFeed. Having
two separate classes makes it difficult to:
- reason about
- process a collection of both MediaFeed and TagMediaFeed
Point #2 is exacerbated by the returned MediaFeed type from the
InstagramClient#getRecentMediaNextPage API. This API flow starts with
an initial TagMediaFeed and fetches subsequence MediaFeed objects
which makes using Java 8 streams difficult.
*Solution*
Deprecate the use of TagMediaFeed in favor of MediaFeed. APIs were
added to InstagramClient to fetch tagged media with a MediaFeed
response type.
Deprecation notices were added conveying API removal in next major
version (likely 2) and what APIs you should use now to avoid
deprecation warnings.
fixes #179

deprecate TagMediaFeed and the API using it

---

pom.xml

Motivation
Including logger implementations within a library can cause logging
issues when including in an application. Usually an application will
have specific logging needs and will provide the slf4j log
implementation.
Solution
This change removes log4j dependencies from the compile/runtime
classpath of jInstagram. Only the slf4j API is included.
Additionally logback-classic (slf4j logger impl) is added on the
test classpath for test log debugging.

removed logger impl deps from compile/runtime cp

---

src/main/java/org/jinstagram/InstagramBase.java
src/main/java/org/jinstagram/InstagramConfig.java
src/main/java/org/jinstagram/http/Response.java

Motivation
The instagram API, over HTTP 1.1, occasionally exhibits these
issues:
- socket reset of TCP connection
- partial JSON response stream leading to JSON parse errors
This addresses the errors by retrying the request when either a
socket exception or JSON parse error occurs.
It is worth noting that the instagram API over HTTP2 does not
seem to have these issues. It would be much more work to allow
HTTP 2, at this point, because Java does not support in their
native APIs.
Solution
Provide a configurable setting to retry the request on stream
failure.
Only one retry is attempted. If the response failed again the
errors will be propagated.
Missing
A test should be provided to check the retry logic.
retry on invalid json response
single retry; must be enabled in InstagramConfig
fix …

add retry logic on response stream failure

---

src/main/java/org/jinstagram/http/Response.java

HTTP headers are case-insensitive (RFC 7230 / RFC 7540). Thus the
headers are stored using a java.util.TreeMap with a
String.CASE_INSENSITIVE_ORDER comparator.
This is a real life issue under Google App Engine, described here:
https://github.com/sachin-handiekar/jInstagram/issues/79

Make HTTP header keys case insensitive, make header parsing null safe

---

src/main/java/org/jinstagram/entity/common/InstagramErrorResponse.java

Hi there!
I've had issues with this statement filling up my log files. This line is thrown when we get RateLimited and so appears quite frequently in the application, it's also very chunky. 
Since it's `System.out.println`, it's not even possible to filter out using logback. My suggestion is to remove it, since the message is viewable on the exception anyway. 
Example statement any time a RateLimit exception appears:
```
Printing json : {"error_type": "OAuthRateLimitException", "code": 429, "error_message": "You have exceeded the maximum number of requests per hour. You have performed a total of 6000 requests in the la
Printing jsonElement : {"error_type":"OAuthRateLimitException","code":429,"error_message":"You have exceeded the maximum number of requests per hour. You have performed a …
```

Remove System.out.println from InstagramErrorResponse
